### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Trak-Hero** [roboflow/roboflow-api-snippets#18]
I tried running the webcam async for python but I am given this error.

Traceback (most recent call last):
  File "/Users/23trak_p/Desktop/roboflow/roboflow_webcam_tutorial.py", line 4, in <module>
    config = json.load(f)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mtraor3** [comment]
@Trak-Hero How is your config file, [`roboflow_config.json`](https://github.com/roboflow/roboflow-api-snippets/blob/main/Python/webcam/roboflow_config.sample.json) formatted? Additionally, is it in the same directory as the [`infer_async.py` file](https://github.com/roboflow/roboflow-api-snippets/blob/main/Python/webcam/infer-async.py) you're running? It is expecting it to be in the same directory

<img width="320" alt="image" src="https://github.com/roboflow/roboflow-api-snippets/assets/89935638/8882286b-6df8-4e89-9b74-3dec8bb5bd96">

Example formatting for `roboflow_config.json` - ensure you have used double quotes, rather than single quotes, where necessary:
```
{
    "__comment1": "Obtain these values via Roboflow",
    "ROBOFLOW_API_KEY": "your_api_key",
    "ROBOFLOW_MODEL": "your_model",
    "ROBOFLOW_SIZE": 640,

    "__comment2": "The following are only needed for infer-async.py",
    "FRAMERATE": 24,
    "BUFFER": 0.5
}
```

"ROBOFLOW_SIZE": 640, is based on your Resize value set when you generated the version your model is trained on. Resize of 640x640 --> set value to `640`.

<img width="512" alt="image" src="https://github.com/roboflow/roboflow-api-snippets/assets/89935638/bdf61a75-98ee-4b0e-896a-c65066de726b">

**Comment by mtraor3** [comment]
Gathering the values for `"your_api_key"` and `"your_model"`: https://docs.roboflow.com/roboflow-workspaces/model-deployment-requirements

In this case, `"your_model"` will be replaced by `"your_model_id/version_number"`
* e.g: https://universe.roboflow.com/mohamed-traore-2ekkp/face-detection-mik1i/18:

`"your_model"` becomes: `"face-detection-mik1i/18"`

**Comment by Trak-Hero** [comment]
What if I am using a public model? How will I format the "your model"?
